apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gradle-webapp
  labels:
    app: gradle-webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gradle-webapp
    spec:
      containers:
      - image: gcr.io/hello-world-241305/image-repo:image_tag
        name: gradle-webapp
        ports:
        - containerPort: 8080
