apiVersion: v1
kind: Service
metadata:
  name: gradle-webapp-svc
  labels:
    app: gradle-webapp-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: gradle-webapp
